### ISSUE TITLE
ValueError: `logits` and `labels` must have the same shape, received ((None, 1) vs ()).

### ISSUE THREAD

**Issue by Pusse-01** [CVxTz/kinship_prediction#3]
Please help me to resolve this.

```
`Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Epoch 1/100

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

[<ipython-input-26-0f1203a024ef>](https://localhost:8080/#) in <module>()
    127 model.fit_generator(gen(train, train_person_to_images_map, batch_size=16), use_multiprocessing=True,
    128                     validation_data=gen(val, val_person_to_images_map, batch_size=16), epochs=100, verbose=2,
--> 129                     workers=4, callbacks=callbacks_list, steps_per_epoch=200, validation_steps=100)
    130 
    131 test_path = "../input/test/"

2 frames

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py](https://localhost:8080/#) in autograph_handler(*args, **kwargs)
   1145           except Exception as e:  # pylint:disable=broad-except
   1146             if hasattr(e, "ag_error_metadata"):
-> 1147               raise e.ag_error_metadata.to_exception(e)
   1148             else:
   1149               raise

ValueError: in user code:

    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 860, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 919, in compute_loss
        y, y_pred, sample_weight, regularization_losses=self.losses)
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "/usr/local/lib/python3.7/dist-packages/keras/losses.py", line 1932, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "/usr/local/lib/python3.7/dist-packages/keras/backend.py", line 5247, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    ValueError: `logits` and `labels` must have the same shape, received ((None, 1) vs ()).`
```

**Comment by CVxTz** [comment]
One possible explanation is that you don't have the same dependencies versions (keras, vggface ... )
Good luck

**Comment by Pusse-01** [comment]
@CVxTz yes it worked. Thanks
